travis: use the homebrew-core workflow with bottles during pull-requests
- do not override bintray bottles (do it manually instead).
- on linkage error, don't do anything, just abort. When I was using the
  master branch for building bottles, it made sense; now that I use pull
  requests in order to build them, it does not make sense anymore.
- bottles are pushed only in pull requests now (as unpublished).
- remove --no-push so that pr-1234 tag is pushed with --ci-upload

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,18 +5,19 @@
 # - cron/api (api is when you select 'trigger build' in travis): in this mode,
 #   all the formulas are tested to make sure that there is no shared lib
 #   breakage
-# - push to master: in this mode, the updated formulas are built and bottled
-#   and the bottles are pushed to bintray, commited and pushed.
-# - pull-request: same as 'push on master' but without bintray and commit.
+# - push to master: does nothing
+# - pull-request: in this mode, the updated formulas are built and bottled
+#   and the bottles are pushed to bintray as 'unpublished'. The DSL commit
+#   is pushed as a tag, e.g., 'pr-1234', which us unrelated to master.
 
 language: ruby
-if: tag IS blank # build is disabled on tags (no rationale actually)
+if: tag IS blank AND NOT type IN (push)
 env:
   global:
     - HOMEBREW_BINTRAY_USER=maelvalais
-    - TAP_BOTTLE_DOMAIN=https://dl.bintray.com/touist
+    - TAP_BOTTLE_DOMAIN=https://dl.bintray.com/maelvalais
     - AWS_REGION=eu-west-1 # needed because the aws-sdk-s3 gem errors without it
-    - BUCKET=homebrew-touist-travis
+    - BUCKET=homebrew-amc
     # Beyond these global variables, you also need to set some secret variables
     # in your travis-ci settings:
     # - AWS_ACCESS_KEY_ID
@@ -24,16 +25,18 @@ env:
     # - GITHUB_TOKEN                   (for pushing bottle DSL commits)
     # - HOMEBREW_BINTRAY_KEY           (for the Bintray repo)
 
-# Note: I removed $HOME/Library/Caches/Homebrew from the caches
-# because it was enormous (~2GB for the 4 jobs). This is because
-# this folder is already present on osx images and it is big.
-# Note2: I also removed $HOME/.cache/Homebrew (cache of Linuxbrew)
-# because it was also storing some logs, making the cache rebuilt
-# every time.
+# (1) remember tu use 'brew cleanup -s' at the end of the travis script;
+# otherwise, the $HOME/Library/Caches/Homebrew folder will be enormous
+# (~2GB for the 4 jobs). This is because this folder is already present on
+# osx images and it is big.
+# (2) I also removed $HOME/.cache/Homebrew (cache of Linuxbrew) because it
+# was also storing some logs, making the cache rebuilt every time.
 cache:
   directories:
     - "$HOME/.cache/pip"
     - "$HOME/.gem/ruby"
+    #- "$HOME/Library/Caches/Homebrew" # (1)
+    #- "$HOME/.cache/Homebrew"        # (2)
 
 install:
   # the official test-bot won't let you run inside TravisCI, so we use
@@ -62,21 +65,20 @@ install:
   # brew cask uninstall... it will fail on the deprecation notice.
   # Unless I am in 'brew test-bot', I don't want to fail on warnings.
 
+# WARNING: I discovered that 'set -e' is breaking Travis CI. I was using for
+# stopping a multiple-lines command as soon as one of the commands fails.
+# After having 'set -e', internal travis commands may stop working, e.g.:
+#   /Users/travis/.travis/job_stages: line 57: shell_session_update: command not found
+# is an internal error that shouldn't stop the script for continuing, but
+# because of 'set -e', the whole internal Travis CI script stops.
+# Conclusion: avoid using 'set -e' and more generally avoid for-loops and
+# multi-line commands that should fail when one of the commands fails.
 script:
   - |
     if [[ $TRAVIS_EVENT_TYPE =~ cron|api ]]; then
-      brew install *.rb && brew test *.rb || exit 123
-      for f in *.rb; do
-        if ! brew linkage --test ${f/\.rb/}; then
-          rev=$(grep revision $f | sed 's/^[^0-9]*\([0-9]*\)$/\1/')
-          sed -i "s/revision [0-9]*/revision $(expr $rev + 1)" $f
-          git commit -a -m "${f/\.rb/}: bump from revision $rev to $(expr $rev + 1) (brew linkage)"
-          git log -n2 -p
-          git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
-        fi
-      done
+      brew install *.rb && brew test *.rb && brew linkage --test *.rb || exit 123
     fi
-  - if [[ $TRAVIS_EVENT_TYPE =~ push|pull_request ]]; then brew test-bot; fi
+  - if [[ $TRAVIS_EVENT_TYPE =~ pull_request ]]; then brew test-bot; fi
   - ls *.bottle*.* || echo "==> No bottle created here"
 
 jobs:
@@ -140,10 +142,11 @@ jobs:
           /opt/pyenv/shims/*-config /usr/local/clang-*/bin/llvm-config
       before_cache:
         - brew cleanup
-
+    # Uploading to bintray (as unpublished bottle) and pushing a tag to the
+    # repo are only enabled on pull_requests.
     - <<: *run-on-linux
       stage: deploy
-      if: branch = master AND NOT type IN (pull_request, cron, api)
+      if: branch = master AND type IN (pull_request)
       os: linux
       env: OS=any_linux
       script:
@@ -152,35 +155,26 @@ jobs:
           ruby <<EOF || true
           require 'aws-sdk-s3'; s3 = Aws::S3::Resource.new
           s3.bucket("$BUCKET").objects(prefix:"$TRAVIS_BUILD_NUMBER/").each { |o| o.download_file(o.key.to_s.gsub(/^\d*\/(.*)/, '\1')) }
+
         # This hook will add [ci skip] the the commit messages for bottle DSL
         # so that travis-ci does not re-build a duplicate bottle on pushing.
         - echo 'echo "\n\n[ci skip]" >> "$1"' > .git/hooks/commit-msg; chmod +x .git/hooks/commit-msg
-        # We fail 'silently' if no bottle is found.
+
+        # (1) We fail 'silently' if no bottle is found.
+        # (2) A trick so that 'prefix' and 'cellar' are removed if they are
+        # equal to DEFAULT_PREFIX and DEFAULT_CELLAR even though we run
+        # 'brew bottle' on a linux setup.
+        # (3) In 'brew --ci--upload', --git-name is the name of the fork
+        # where the pr-1234 (or testing-98 when not in a PR) tag is pushed.
+        # In my case, I use the 'main' instead of a fork.
         - |
-          if ls *.{json,tar.gz}; then
-            # This is a trick so that 'prefix' and 'cellar' are removed if they
-            # are equal to DEFAULT_PREFIX and DEFAULT_CELLAR even though we run
-            # 'brew bottle' on a linux setup.
-            sed -i 's:/usr/local:/home/linuxbrew/.linuxbrew:g' *.json;
-            # Travis does not provide a high_sierra image yet, but I can use the
-            # sierra one and pretend it is a high_sierra bottle. I test them regularly in
-            # case it doesn't work.
-            ls *.sierra.bottle.json | while read json; do
-              sed 's/sierra/high_sierra/g' $json > ${json/sierra/high_sierra};
-              bottle=`ls ${json/bottle*/}*.tar.gz`;
-              cp ${bottle} ${bottle/sierra/high_sierra};
-            done;
-            # Note that --git-name also determines where the push will be done!
-            # In my case, I disabled the push using '--no-push' so it wont push
-            # to maelvalais/homebrew-touist.
-            git fetch && git checkout master;
-            brew test-bot --ci-upload --no-push --overwrite --git-name=touist --bintray-org=touist --verbose;
-            # git fetch && git rebase && git push https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master;
+          if ls *.{json,tar.gz}; then                                  # (1)
+            sed -i 's:/usr/local:/home/linuxbrew/.linuxbrew:g' *.json; # (2)
+            brew test-bot --ci-upload --git-name=maelvalais --git-email=mael.valais@gmail.com --bintray-org=maelvalais --verbose;
           else
             echo "==> No bottle found in the bucket, skipping --ci-upload";
           fi
-      after_script:
-        # nothing
+      after_script: true # nothing
 
 after_script:
   # In case the AWS_SECRET_ACCESS_KEY and AWS_SECRET_ACCESS_KEY are not
